In [1]:
import pandas as pd
import numpy as np
from scipy.signal import argrelextrema

df = pd.read_csv("AAPL.csv")

In [2]:
print(df)

         Date        Open        High         Low       Close
0    17-10-17  159.779999  160.869995  159.229996  160.470001
1    18-10-17  160.419998  160.710007  159.600006  159.759995
2    19-10-17  156.750000  157.080002  155.020004  155.979996
3    20-10-17  156.610001  157.750000  155.960007  156.250000
4    23-10-17  156.889999  157.690002  155.500000  156.169998
5    24-10-17  156.289993  157.419998  156.199997  157.100006
6    25-10-17  156.910004  157.550003  155.270004  156.410004
7    26-10-17  157.229996  157.830002  156.779999  157.410004
8    27-10-17  159.289993  163.600006  158.699997  163.050003
9    30-10-17  163.889999  168.070007  163.720001  166.720001
10   31-10-17  167.899994  169.649994  166.940002  169.039993
11   01-11-17  169.869995  169.940002  165.610001  166.889999
12   02-11-17  166.600006  168.500000  165.279999  168.110001
13   03-11-17  174.000000  174.259995  171.119995  172.500000
14   06-11-17  172.369995  174.990005  171.720001  174.250000
15   07-11-17  173.910004  175.250000  173.600006  174.809998
16   08-11-17  174.660004  176.240005  174.330002  176.240005
17   09-11-17  175.110001  176.100006  173.139999  175.880005
18   10-11-17  175.110001  175.380005  174.270004  174.669998
19   13-11-17  173.500000  174.500000  173.399994  173.970001
20   14-11-17  173.039993  173.479996  171.179993  171.339996
21   15-11-17  169.970001  170.320007  168.380005  169.080002
22   16-11-17  171.179993  171.869995  170.300003  171.100006
23   17-11-17  171.039993  171.389999  169.639999  170.149994
24   20-11-17  170.289993  170.559998  169.559998  169.979996
25   21-11-17  170.779999  173.699997  170.779999  173.139999
26   22-11-17  173.360001  175.000000  173.050003  174.960007
27   24-11-17  175.100006  175.500000  174.649994  174.970001
28   27-11-17  175.050003  175.080002  173.339996  174.089996
29   28-11-17  174.300003  174.869995  171.860001  173.070007
..        ...         ...         ...         ...         ...
223  06-09-18  226.229996  227.350006  221.300003  223.100006
224  07-09-18  221.850006  225.369995  220.710007  221.300003
225  10-09-18  220.949997  221.850006  216.470001  218.330002
226  11-09-18  218.009995  224.300003  216.559998  223.850006
227  12-09-18  224.940002  225.000000  219.839996  221.070007
228  13-09-18  223.520004  228.350006  222.570007  226.410004
229  14-09-18  225.750000  226.839996  222.520004  223.839996
230  17-09-18  222.149994  222.949997  217.270004  217.880005
231  18-09-18  217.789993  221.850006  217.119995  218.240005
232  19-09-18  218.500000  219.619995  215.300003  218.369995
233  20-09-18  220.240005  222.279999  219.149994  220.029999
234  21-09-18  220.779999  221.360001  217.289993  217.660004
235  24-09-18  216.820007  221.259995  216.630005  220.789993
236  25-09-18  219.750000  222.820007  219.699997  222.190002
237  26-09-18  221.000000  223.750000  219.759995  220.419998
238  27-09-18  223.820007  226.440002  223.539993  224.949997
239  28-09-18  224.789993  225.839996  224.020004  225.740005
240  01-10-18  227.949997  229.419998  226.350006  227.259995
241  02-10-18  227.250000  230.000000  226.630005  229.279999
242  03-10-18  230.050003  233.470001  229.779999  232.070007
243  04-10-18  230.779999  232.350006  226.729996  227.990005
244  05-10-18  227.960007  228.410004  220.580002  224.289993
245  08-10-18  222.210007  224.800003  220.199997  223.770004
246  09-10-18  223.639999  227.270004  222.250000  226.869995
247  10-10-18  225.460007  226.350006  216.050003  216.360001
248  11-10-18  214.520004  219.500000  212.320007  214.449997
249  12-10-18  220.419998  222.880005  216.839996  222.110001
250  15-10-18  221.160004  221.830002  217.270004  217.360001
251  16-10-18  218.929993  222.990005  216.759995  222.149994
252  17-10-18  222.300003  222.639999  219.339996  221.190002

[253 rows x 5 columns]

In [3]:
e = np.array(df['Close'])
print(e)

e.ndim

#import matplotlib.pyplot as plt
#plt.plot(x) # looks good

[160.470001 159.759995 155.979996 156.25     156.169998 157.100006
 156.410004 157.410004 163.050003 166.720001 169.039993 166.889999
 168.110001 172.5      174.25     174.809998 176.240005 175.880005
 174.669998 173.970001 171.339996 169.080002 171.100006 170.149994
 169.979996 173.139999 174.960007 174.970001 174.089996 173.070007
 169.479996 171.850006 171.050003 169.800003 169.639999 169.009995
 169.320007 169.369995 172.669998 171.699997 172.270004 172.220001
 173.970001 176.419998 174.539993 174.350006 175.009995 175.009995
 170.570007 170.600006 171.080002 169.229996 172.259995 172.229996
 173.029999 175.       174.350006 174.330002 174.289993 175.279999
 177.089996 176.190002 179.100006 179.259995 178.460007 177.
 177.039993 174.220001 171.110001 171.509995 167.960007 166.970001
 167.429993 167.779999 160.5      156.490005 163.029999 159.539993
 155.149994 156.410004 162.710007 164.339996 167.369995 172.990005
 172.429993 171.850006 171.070007 172.5      175.5      178.970001
 178.389999 178.119995 175.       176.210007 176.820007 176.669998
 175.029999 176.940002 179.979996 181.720001 179.970001 178.440002
 178.649994 178.020004 175.300003 175.240005 171.270004 168.850006
 164.940002 172.770004 168.339996 166.479996 167.779999 166.679993
 168.389999 171.610001 172.800003 168.380005 170.050003 173.25
 172.440002 174.139999 174.729996 175.820007 178.240005 177.839996
 172.800003 165.720001 165.240005 162.940002 163.649994 164.220001
 162.320007 165.259995 169.100006 176.570007 176.889999 183.830002
 185.160004 186.050003 187.360001 190.039993 188.589996 188.149994
 186.440002 188.179993 186.990005 186.309998 187.630005 187.160004
 188.360001 188.149994 188.580002 187.899994 187.5      186.869995
 190.240005 191.830002 193.309998 193.979996 193.460007 191.699997
 191.229996 192.279999 190.699997 190.800003 188.839996 188.740005
 185.690002 186.5      185.460007 184.919998 182.169998 184.429993
 184.160004 185.5      185.110001 187.179993 183.919998 185.399994
 187.970001 190.580002 190.350006 187.880005 191.029999 191.330002
 190.910004 191.449997 190.399994 191.880005 191.440002 191.610001
 193.       194.820007 194.210007 190.979996 189.910004 190.289993
 201.5      207.389999 207.990005 209.070007 207.110001 207.25
 208.880005 207.529999 208.869995 209.75     210.240005 213.320007
 217.580002 215.460007 215.039993 215.050003 215.490005 216.160004
 217.940002 219.699997 222.979996 225.029999 227.630005 228.360001
 226.869995 223.100006 221.300003 218.330002 223.850006 221.070007
 226.410004 223.839996 217.880005 218.240005 218.369995 220.029999
 217.660004 220.789993 222.190002 220.419998 224.949997 225.740005
 227.259995 229.279999 232.070007 227.990005 224.289993 223.770004
 226.869995 216.360001 214.449997 222.110001 217.360001 222.149994
 221.190002]

1

In [4]:
def get_minmax(e):
    minimum = np.asarray(argrelextrema(e, np.less, order=2))
    maximum = np.asarray(argrelextrema(e, np.greater, order=2))
    return minimum, maximum

In [5]:
c=get_minmax(e)
print(c)

(array([[  2,  21,  24,  30,  35,  45,  48,  51,  58,  71,  75,  78,  86,
         92,  96, 108, 111, 117, 129, 132, 144, 147, 155, 172, 178, 183,
        188, 196, 202, 212, 225, 230, 234, 237, 248]], dtype=int64), array([[ 10,  16,  27,  38,  43,  55,  63,  73,  76,  83,  89,  94,  99,
        109, 116, 124, 141, 145, 152, 159, 163, 177, 181, 189, 193, 201,
        204, 210, 221, 228, 242, 246, 251]], dtype=int64))

In [6]:
e[c[0]], e[c[1]] # access index's values here

(array([[155.979996, 169.080002, 169.979996, 169.479996, 169.009995,
         174.350006, 170.570007, 169.229996, 174.289993, 166.970001,
         156.490005, 155.149994, 171.070007, 175.      , 175.029999,
         164.940002, 166.479996, 168.380005, 162.940002, 162.320007,
         186.440002, 186.309998, 186.869995, 182.169998, 183.919998,
         187.880005, 190.399994, 189.910004, 207.110001, 215.039993,
         218.330002, 217.880005, 217.660004, 220.419998, 214.449997]]),
 array([[169.039993, 176.240005, 174.970001, 172.669998, 176.419998,
         175.      , 179.259995, 167.779999, 163.029999, 172.990005,
         178.970001, 176.820007, 181.720001, 172.770004, 172.800003,
         178.240005, 190.039993, 188.179993, 188.580002, 193.979996,
         192.279999, 187.179993, 190.580002, 191.880005, 194.820007,
         209.070007, 208.880005, 217.580002, 228.360001, 226.410004,
         232.070007, 226.869995, 222.149994]]))

In [15]:
c_merged = np.concatenate(maximum, minimum)
c_merged = np.array(c_merged)
print(c_merged)

TypeError: only integer scalar arrays can be converted to a scalar index

In [25]:
minimum = np.asarray(argrelextrema(e, np.less, order=2))
maximum = np.asarray(argrelextrema(e, np.greater, order=2))

print(minimum)
print(maximum)

print(minimum.type)

#shelf = []
#for value in minimum:
    #minimum[0] += shelf

[[  2  21  24  30  35  45  48  51  58  71  75  78  86  92  96 108 111 117
  129 132 144 147 155 172 178 183 188 196 202 212 225 230 234 237 248]]
[[ 10  16  27  38  43  55  63  73  76  83  89  94  99 109 116 124 141 145
  152 159 163 177 181 189 193 201 204 210 221 228 242 246 251]]

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [ ]:
combined = [] # when they are same length
for i in range(len(minimum)):
    combined.append(maximum(i))
    combined.append(minimum(i))

In [ ]:
# define shape W
# the 2nd leg is 10 - 20% of the first leg

In [ ]:
# Now I need for all these minimas & maximas values:Compare it to next to each other to know how many of them
# satifies the condition of being the range of 4% (but I'm assuming it is 4% of the swing not the value(price)) figure out 
# the swings high -> low & vv.get 20% of the swings to get the pullback and now the 4% is easy peazy  Get the swings done is 
# the next job